include ../Make.defines

PROGS =	test1 test2

all:	${PROGS}

test1:	test1.o
		${CC} ${CFLAGS} -o $@ test1.o ${LIBS}

test2:	test2.o
		${CC} ${CFLAGS} -o $@ test2.o ${LIBS}

prodcons3:	prodcons3.o
		${CC} ${CFLAGS} -o $@ prodcons3.o ${LIBS}

prodcons4:	prodcons4.o
		${CC} ${CFLAGS} -o $@ prodcons4.o ${LIBS}

prodcons5:	prodcons5.o
		${CC} ${CFLAGS} -o $@ prodcons5.o ${LIBS}

prodcons6:	prodcons6.o
		${CC} ${CFLAGS} -o $@ prodcons6.o ${LIBS}

prodcons7:	prodcons7.o
		${CC} ${CFLAGS} -o $@ prodcons7.o ${LIBS}

test1:	test1.o
		${CC} ${CFLAGS} -o $@ test1.o ${LIBS}

test2:	test2.o
		${CC} ${CFLAGS} -o $@ test2.o ${LIBS}

test3:	test3.o
		${CC} ${CFLAGS} -o $@ test3.o ${LIBS}

test4:	test4.o
		${CC} ${CFLAGS} -o $@ test4.o ${LIBS}

clean:
		rm -f ${PROGS} ${CLEANFILES}
